markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
baseurl: /
exclude: ['README.md', 'other']
include: ['.htaccess']
pygments: true
